name: Master

# Pushes to Master will deploy to Cloudhub-Dev immediately, but Cloudhub-QA will require approval

on:
  branch:
    branches:
      - 'master'

  # Manual Trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Cache Maven Dependencies
      - name: A) Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Build Maven
      - name: B) Build Maven
        shell: bash
        env:
          encryption: ${{ secrets.ENCRYPTION_KEY }}
        run:  |
          mvn -B test "-DencryptionKey=${encryption}"
          mkdir staging && cp target/*.jar staging

      - name: C) Enumerate Maven Version
        shell: bash
        run: |
          bash "${PWD}/automation/version-enumerate.sh"

      - name: D) Commit Version Update
        uses: stefanzweifel/git-auto-commit-action@v4
          commit_message: Enumerate Maven Version
          file_pattern: pom.xml

      # Upload Artifact within Workflow scope
      - name: E) Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: staging

  dev-deploy:
    needs: build
    environment: dev
    env:
      environment: dev
      repository: ${{ github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: A) Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: artifact
          path: staging

      - name: B) Deploy to Cloudhub
        shell: bash
        env:
          encryption: ${{ secrets.ENCRYPTION_KEY }}
          credentials: ${{ secrets.ANYPOINT_CREDENTIALS_FILE }}
          clientId: ${{ secrets.ANYPOINT_PLATFORM_CLIENT_ID }}
          clientSecret: ${{ secrets.ANYPOINT_PLATFORM_CLIENT_SECRET }}
        run: bash "${PWD}/automation/github-runner.sh"

#      - name: C.) Post-deployment API Tests
#        shell: bash
#        run: |
#          sudo npm i -g newman@latest
#          repoName="${repository##*/}"
#          newman run "automation/tests/${repoName}.postman_collection.json" -e "automation/tests/${environment}.postman_environment.json"

  qa-deploy:
    needs: dev-deploy
    environment: qa
    env:
      environment: qa
      repository: ${{ github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: A) Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: artifact
          path: staging

      - name: B) Deploy to Cloudhub
        shell: bash
        env:
          encryption: ${{ secrets.ENCRYPTION_KEY }}
          credentials: ${{ secrets.ANYPOINT_CREDENTIALS_FILE }}
          clientId: ${{ secrets.ANYPOINT_PLATFORM_CLIENT_ID }}
          clientSecret: ${{ secrets.ANYPOINT_PLATFORM_CLIENT_SECRET }}
        run: bash "${PWD}/automation/github-runner.sh"

#      - name: C.) Post-deployment API Tests
#        shell: bash
#        run: |
#          sudo npm i -g newman@latest
#          repoName="${repository##*/}"
#          newman run "automation/tests/${repoName}.postman_collection.json" -e "automation/tests/${environment}.postman_environment.json"
