name: Master

# Pushes to Master will enumerate the pom file and deploy to Cloudhub-Dev immediately

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Cache Maven Dependencies
      - name: A) Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Increase POM file version
      - name: B) Enumerate Maven Version
        shell: bash
        run: |
          bash "${PWD}/automation/version-enumerate.sh"

      # Build Maven
      - name: C) Build Maven
        shell: bash
        env:
          encryption: ${{ secrets.ENCRYPTION_KEY }}
        run:  |
          mvn -B package "-DencryptionKey=${encryption}"
          mkdir staging && cp target/*.jar staging

      # Upload Artifact within Workflow scope
      - name: D) Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: staging

  dev-deploy:
    needs: build
    environment: dev
    env:
      environment: dev
      repository: ${{ github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: A) Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: artifact
          path: staging

      - name: B) Deploy to Cloudhub
        shell: bash
        env:
          encryption: ${{ secrets.ENCRYPTION_KEY }}
          credentials: ${{ secrets.ANYPOINT_CREDENTIALS_FILE }}
          clientId: ${{ secrets.ANYPOINT_PLATFORM_CLIENT_ID }}
          clientSecret: ${{ secrets.ANYPOINT_PLATFORM_CLIENT_SECRET }}
        run: bash "${PWD}/automation/github-runner.sh"

#      - name: C.) Post-deployment API Tests
#        shell: bash
#        run: |
#          sudo npm i -g newman@latest
#          repoName="${repository##*/}"
#          newman run "automation/tests/${repoName}.postman_collection.json" -e "automation/tests/${environment}.postman_environment.json"

  version:
    needs: dev-deploy
    runs-on: ubuntu-latest
    steps:
    # Increase POM file version
    - name: A) Enumerate Maven Version
      shell: bash
      run: |
        bash "${PWD}/automation/version-enumerate.sh"

    # Commit the increase in the pom file to the branch
    # Github actions cannot recurse on trigger
    - name: B) Commit Version Update
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Enumerate Maven Version
        file_pattern: pom.xml
